baseURL: "https://guide.lucyber.club"
title: "LU Cyber Guide"
enableRobotsTXT: true
paginate: 50
theme: PaperMod

buildDrafts: false
buildFuture: false
buildExpired: false
pygmentsUseClasses: true

minify:
    disableXML: true
    minifyOutput: true

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: "LU Cyber Guide"
    description: "Liberty University Cyber Defense Club Cyber Guide"
    keywords: [Blog, Portfolio, PaperMod]
    author: "Liberty University Cyber Defense Club"
    # author: ["Me", "You"] # multiple authors
    images: ["<link or path of image for opengraph, twitter-cards>"]
    DateFormat: "January 2, 2006"
    defaultTheme: light # dark, light
    disableThemeToggle: true

    ShowReadingTime: true
    ShowShareButtons: false
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    disableSpecial1stPost: true
    disableScrollToTop: false
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: true
    tocopen: false

    #assets:
        # disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        #favicon: "<link / abs url>"
        #favicon16x16: "<link / abs url>"
        #favicon32x32: "<link / abs url>"
        #apple_touch_icon: "<link / abs url>"
        #safari_pinned_tab: "<link / abs url>"


    # home-info mode
    homeInfoParams:
        Title: "Welcome"
        Content: Welcome to the Liberty University Cyber Defense Club Cyberguide! This guide is designed for students to learn about cyber security by utilizing the provided resources. As time goes on more content will be added to this site and the guide will continue to be updated and improved.

    # socialIcons:
    #     - name: twitter
    #       url: "https://twitter.com/"
    #     - name: stackoverflow
    #       url: "https://stackoverflow.com"
    #     - name: github
    #       url: "https://github.com/"

    # cover:
    #     hidden: true # hide everywhere but not in structured data
    #     hiddenInList: true # hide on list pages and home
    #     hiddenInSingle: true # hide on single page

    editPost:
        URL: "https://github.com/lucyber/cyberguide/blob/master/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
menu:
    header:
        - identifier: about
          name: About
          url: https://lucyber.club/#about
        - identifier: connect
          name: Connect
          url: https://lucyber.club/#contact
        - identifier: cyberguide
          name: Cyberguide
          url:  /
