---
baseURL: https://localhost:1313/
title: LU Cyberguide
theme: geekdoc
pygmentsUseClasses: true
pygmentsCodeFences: true
pluralizelisttitles: ""

# Geekdoc configuration
disablePathToLower: true
enableGitInfo: true

# Needed for mermaid shortcodes
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 1
    endLevel: 9

params:
  geekdocToC: 3

  geekdocRepo: https://github.com/xoxys/hugo-geekdoc
  geekdocEditPath: edit/master/exampleSite/content

  geekdocSearch: true

  geekdocLegalNotice: https://thegeeklab.de/legal-notice/#contact-information
  geekdocPrivacyPolicy: https://thegeeklab.de/legal-notice/#privacy-policy
