name: hugo build and deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master  # Set a branch to deploy
      
jobs:
  deploy:
    runs-on: zetagroup-runner
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
          
      - name: Test
        run: |
          echo Hey there buddy!
          ls -la
          
#       - name: Setup Node.js environment
#         uses: actions/setup-node@v1.4.3
#         with:
#           node-version: "14.x"
          
#       - name: Setup Hugo
#         uses: peaceiris/actions-hugo@v2
#         with:
#           hugo-version: '0.75.1'

#       - name: Build Theme
#         run: |
#           cd themes/geekdoc
#           npm install
#           gulp default
#           cd ../..
        
#       - name: Build Hugo
#         run: hugo --minify
        
#       - name: Deploy
#         uses: easingthemes/ssh-deploy@v2.1.5
#         env:
#             SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
#             ARGS: "-rltgoDzvO --delete"
#             SOURCE: "public/"
#             REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
#             REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
#             REMOTE_USER: ${{ secrets.REMOTE_USER }}
#             TARGET: ${{ secrets.REMOTE_TARGET }}
